### ISSUE TITLE
BufSet should ignore duplicates instead of failing

### ISSUE THREAD

**Issue by mkotsbak** [MetaStack-pl/MetaRx#6]
Inserting a duplicate value into a BufSet gives:
 assert(!elements.contains(value), "Value already exists")

It should instead work as (immutable) Scala Set trait, which ignores duplicates, or http://www.scala-lang.org/api/current/index.html#scala.collection.mutable.LinkedHashSet@add%28elem:A%29:Boolean which ignores and returns a flag indicating if it was a duplicate.

**Comment by tindzk** [comment]
I deliberately made this decision because it improves the performance of all operations defined in the ``Delta`` trait. Otherwise every operation would either have to query the current state (and consequently, could not be implemented in the ``Delta`` trait) or maintain a copy of the entire data structure. With the current design, [``size``](https://github.com/MetaStack-pl/MetaRx/blob/master/shared/src/main/scala/pl/metastack/metarx/BufSet.scala#L44) could be implemented purely in terms of the shape of the delta objects, not taking into account their contents.

In ``Dict``, I provide two helper functions ``insertOrUpdate`` and ``removeIfExists``. I could add ``insertIfNotExists`` and ``removeIfExists`` to ``BufSet``. Can you think of better names?

**Comment by mkotsbak** [comment]
Those utility method would be nice yes. I do something like that now manually. I guess there are no thread issues anyway here as long as it is used in single threaded JS?

**Comment by tindzk** [comment]
Yes, exactly. JavaScript is single-threaded and you will not run into such problems. On the JVM, it should work too as ``produce()`` is a synchronising call, see [this commit](https://github.com/MetaStack-pl/MetaRx/commit/14f4c46a029a785b9c95426da0cebdb674b6c1fd).
